from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression

training_data = [

    "fever cough sore throat",
    "high fever body pain chills",
    "fever headache weakness",
    "fever chills muscle pain",
    "high fever cough fatigue",
    "fever sore throat tiredness",
    "fever dry cough headache",
    "fever body aches weakness",
    "fever chills headache",
    "high fever sore throat",
    "fever cough body pain",
    "fever fatigue chills",
    "fever headache body aches",
    "fever cough weakness",
    "fever throat pain chills",

    "cough runny nose sneezing",
    "cold cough sneezing",
    "runny nose sore throat",
    "runny nose sneezing cough",
    "mild cough runny nose",
    "blocked nose sneezing cough",
    "nasal congestion runny nose",
    "sneezing mild sore throat",
    "stuffy nose cough",
    "runny nose throat discomfort",
    "cold symptoms nasal congestion",
    "sneezing watery eyes runny nose",
    "mild cough blocked nose",
    "runny nose nasal blockage",
    "sneezing sore throat cough",

    "headache nausea vomiting",
    "severe headache dizziness",
    "headache migraine sensitivity light",
    "throbbing headache nausea",
    "severe headache sensitivity light",
    "headache vomiting dizziness",
    "one sided headache",
    "headache sensitivity sound",
    "pulsing headache nausea",
    "severe head pain",
    "headache light sensitivity",
    "headache nausea dizziness",
    "strong headache vomiting",
    "headache worsens with light",
    "throbbing head pain",

    "stomach pain vomiting",
    "abdominal pain nausea",
    "diarrhea stomach pain",
    "stomach cramps diarrhea",
    "abdominal pain vomiting",
    "nausea diarrhea stomach pain",
    "vomiting stomach pain",
    "loose stools abdominal pain",
    "stomach ache nausea",
    "diarrhea vomiting",
    "abdominal cramps diarrhea",
    "stomach discomfort vomiting",
    "frequent diarrhea nausea",
    "stomach cramps vomiting",
    "loose motion stomach pain",

    "chest pain breathing difficulty",
    "chest pressure shortness breath",
    "difficulty breathing chest pain",
    "shortness of breath",
    "chest tightness breathing difficulty",
    "breathing problem chest pain",
    "chest discomfort shortness breath",
    "difficulty taking deep breath",
    "chest pressure breathing problem",
    "trouble breathing",
    "shortness breath chest tightness",
    "breathing difficulty chest discomfort",
    "chest pain shortness breath",
    "heavy breathing chest discomfort",
    "difficulty breathing chest pressure",

    "skin rash itching",
    "red skin itching rash",
    "skin irritation itching",
    "itchy red skin",
    "skin redness itching",
    "red rash itching",
    "dry itchy skin",
    "skin rash redness",
    "itchy skin patches",
    "red skin patches",
    "skin irritation redness",
    "rash with itching",
    "itchy skin rash",
    "red itchy patches",
    "skin inflammation itching",

    "fatigue thirst frequent urination",
    "excessive thirst frequent urination",
    "weakness frequent urination",
    "increased thirst frequent urination",
    "constant thirst weakness",
    "frequent urination tiredness",
    "excessive thirst fatigue",
    "thirst and frequent urination",
    "increased urination weakness",
    "constant thirst tiredness",
    "frequent urination fatigue",
    "unusual thirst weakness",
    "tiredness increased thirst",
    "frequent urination thirst",
    "excessive thirst weakness"

]

labels = [

    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",
    "Flu",

    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",
    "Common Cold",

    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",
    "Migraine",

    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",
    "Stomach Infection",

    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",
    "Respiratory Condition",

    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",
    "Skin Condition",

    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk",
    "Diabetes Risk"

]

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(training_data)

model = LogisticRegression(max_iter=1000)

model.fit(X, labels)

def get_model():

    return model, vectorizer