from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

training_data = [
    "fever cough sore throat",
    "high fever body pain chills",
    "fever headache weakness",
    "cough runny nose sneezing",
    "cold cough sneezing",
    "runny nose sore throat",
    "headache nausea vomiting",
    "severe headache dizziness",
    "headache migraine sensitivity light",
    "stomach pain vomiting",
    "abdominal pain nausea",
    "diarrhea stomach pain",
    "chest pain breathing difficulty",
    "chest pressure shortness breath",
    "difficulty breathing chest pain",
    "skin rash itching",
    "red skin itching rash",
    "skin irritation itching",
    "fatigue thirst frequent urination",
    "excessive thirst frequent urination",
    "weakness frequent urination",

    "fever chills body aches",
    "high temperature cough fatigue",
    "fever sore throat tiredness",
    "fever dry cough headache",
    "fever muscle pain weakness",
    "fever chills headache",
    "high fever sore throat",
    "fever cough body pain",
    "fever fatigue chills",
    "fever headache body aches",
    "fever cough weakness",
    "fever throat pain chills",
    "fever tiredness muscle pain",
    "high fever headache",
    "fever cough sore throat weakness",
    "fever chills muscle weakness",
    "fever body pain tiredness",
    "fever cough headache fatigue",
    "fever chills sore throat",
    "fever body aches cough",
    "fever weakness chills",
    "fever headache tiredness",
    "high temperature body pain",
    "fever cough muscle aches",
    "fever sore throat headache",
    "fever chills fatigue",
    "fever dry cough weakness",
    "fever headache chills",
    "fever body pain cough",
    "fever throat irritation weakness",
    "fever tiredness headache",
    "fever cough chills weakness",
    "fever chills body weakness",
    "fever cough muscle weakness",
    "fever headache sore throat",
    "fever chills body pain",
    "high fever cough tiredness",
    "fever sore throat chills",
    "fever headache fatigue",
    "fever cough body weakness",
    "fever muscle aches chills",
    "high temperature fever weakness",
    "fever dry cough body pain",
    "fever sore throat headache",
    "fever chills cough",
    "fever tiredness body aches",
    "high fever muscle pain",
    "fever cough throat pain",
    "fever weakness headache",
    "fever chills sore throat",
    "fever body aches fatigue",
    "fever cough muscle pain",
    "fever headache chills",
    "high fever tiredness",
    "fever throat irritation cough",
    "fever weakness body pain",
    "fever chills headache fatigue",
    "fever cough sore throat chills",
    "fever body pain headache",
    "high temperature chills weakness",
    "fever fatigue muscle aches",
    "fever cough headache chills",

    "sneezing runny nose",
    "blocked nose cough",
    "stuffy nose sneezing",
    "runny nose mild cough",
    "sneezing sore throat",
    "nasal congestion sneezing",
    "watery nose cough",
    "cold symptoms runny nose",
    "mild cough sneezing",
    "runny nose throat irritation",
    "blocked nose sore throat",
    "sneezing nasal congestion",
    "runny nose watery eyes",
    "cough nasal congestion",
    "sneezing cough runny nose",
    "mild cold symptoms",
    "stuffy nose sore throat",
    "runny nose sneezing cough",
    "nasal congestion mild cough",
    "sneezing blocked nose",
    "watery eyes runny nose",
    "cold cough nasal congestion",
    "mild sore throat cough",
    "nose blockage sneezing",
    "runny nose mild sore throat",
    "sneezing throat irritation",
    "cough stuffy nose",
    "nasal congestion sore throat",
    "mild cough runny nose",
    "sneezing watery nose",
    "cold symptoms sneezing",
    "blocked nose mild cough",
    "runny nose sneezing cough",
    "mild cough runny nose",
    "blocked nose sneezing cough",
    "nasal congestion runny nose",
    "sneezing mild sore throat",
    "stuffy nose cough",
    "runny nose throat discomfort",
    "cold symptoms nasal congestion",
    "sneezing watery eyes runny nose",
    "mild cough blocked nose",
    "runny nose nasal blockage",
    "sneezing sore throat cough",
    "nasal congestion mild sore throat",
    "watery eyes sneezing",
    "cold cough nasal congestion",
    "mild cold runny nose",
    "sneezing throat irritation cough",
    "blocked nose mild sore throat",
    "runny nose cough sneezing",
    "nasal blockage sneezing",
    "mild cough stuffy nose",
    "cold symptoms sore throat",
    "runny nose watery eyes",
    "sneezing nasal blockage",
    "cough runny nose throat irritation",
    "mild sore throat runny nose",
    "blocked nose watery eyes",
    "cold related sneezing",
    "nasal congestion cough",
    "runny nose mild throat pain",

    "throbbing headache nausea",
    "severe headache sensitivity light",
    "headache vomiting dizziness",
    "one sided headache",
    "headache sensitivity sound",
    "pulsing headache nausea",
    "severe head pain",
    "headache light sensitivity",
    "headache nausea dizziness",
    "strong headache vomiting",
    "headache worsens with light",
    "throbbing head pain",
    "severe headache nausea",
    "head pain sensitivity light",
    "one sided head pain nausea",
    "headache sound sensitivity",
    "repeated severe headache",
    "pulsing headache dizziness",
    "migraine headache nausea",
    "severe headache vomiting",
    "throbbing head pain nausea",
    "headache bright light sensitivity",
    "one sided migraine pain",
    "headache with nausea",
    "severe pulsing headache",
    "headache dizziness light sensitivity",
    "headache nausea sound sensitivity",
    "strong throbbing headache",
    "head pain vomiting",
    "severe one sided headache",
    "migraine dizziness nausea",
    "headache sensitivity to light",
    "migraine headache nausea",
    "severe headache light sensitivity",
    "throbbing headache dizziness",
    "headache nausea light sensitivity",
    "one sided headache dizziness",
    "severe migraine headache",
    "headache vomiting sensitivity",
    "pulsating headache nausea",
    "headache worsened by light",
    "strong headache dizziness",
    "headache sensitivity to sound",
    "severe head pain nausea",
    "one sided migraine headache",
    "throbbing head pain dizziness",
    "headache nausea vomiting",
    "intense headache light sensitivity",
    "migraine pain nausea",
    "headache dizziness vomiting",
    "severe pulsing headache",
    "headache sound and light sensitivity",
    "recurrent severe headache",
    "headache with vomiting",
    "throbbing migraine pain",
    "headache nausea dizziness",
    "severe headache sound sensitivity",
    "pulsing head pain",
    "migraine headache light sensitivity",
    "headache nausea bright light",
    "strong throbbing head pain",
    "severe one sided head pain",

    "stomach cramps diarrhea",
    "abdominal pain vomiting",
    "nausea diarrhea stomach pain",
    "vomiting stomach pain",
    "loose stools abdominal pain",
    "stomach ache nausea",
    "diarrhea vomiting",
    "abdominal cramps diarrhea",
    "stomach discomfort vomiting",
    "frequent diarrhea nausea",
    "stomach cramps vomiting",
    "loose motion stomach pain",
    "nausea abdominal discomfort",
    "stomach ache diarrhea",
    "abdominal pain loose stools",
    "vomiting diarrhea weakness",
    "stomach cramps nausea",
    "stomach pain diarrhea",
    "abdominal pain vomiting diarrhea",
    "nausea stomach cramps",
    "loose stools nausea",
    "frequent loose motion",
    "stomach ache vomiting",
    "abdominal cramps nausea",
    "diarrhea stomach cramps",
    "vomiting nausea stomach pain",
    "digestive discomfort diarrhea",
    "stomach pain loose stools",
    "abdominal discomfort vomiting",
    "nausea diarrhea weakness",
    "stomach cramps loose motion",
    "frequent diarrhea stomach pain",
    "stomach pain nausea",
    "abdominal pain diarrhea",
    "vomiting diarrhea stomach pain",
    "stomach cramps loose stools",
    "nausea vomiting stomach pain",
    "abdominal cramps stomach pain",
    "frequent loose stools",
    "stomach ache vomiting",
    "diarrhea abdominal cramps",
    "nausea stomach discomfort",
    "vomiting abdominal discomfort",
    "stomach cramps diarrhea nausea",
    "loose motion abdominal pain",
    "stomach pain nausea vomiting",
    "diarrhea weakness stomach pain",
    "abdominal pain frequent diarrhea",
    "stomach cramps vomiting nausea",
    "upset stomach loose stools",
    "digestive pain diarrhea",
    "nausea loose motion",
    "stomach discomfort diarrhea",
    "abdominal cramps nausea vomiting",
    "frequent diarrhea stomach cramps",
    "stomach ache loose stools",
    "vomiting and abdominal pain",
    "diarrhea nausea weakness",
    "stomach pain digestive discomfort",
    "loose stools stomach ache",
    "abdominal discomfort diarrhea",
    "stomach cramps frequent diarrhea",

    "shortness of breath",
    "chest tightness breathing difficulty",
    "breathing problem chest pain",
    "chest discomfort shortness breath",
    "difficulty taking breath",
    "chest pressure breathing problem",
    "trouble breathing",
    "shortness breath chest tightness",
    "breathing difficulty chest discomfort",
    "chest pain shortness breath",
    "heavy breathing chest discomfort",
    "difficulty breathing chest pressure",
    "chest tightness breathing problem",
    "breathing problems chest pressure",
    "shortness breath chest pain",
    "chest discomfort breathing difficulty",
    "trouble breathing chest tightness",
    "difficulty breathing deeply",
    "chest pressure shortness breath",
    "breathing difficulty chest tightness",
    "chest pain breathing problem",
    "shortness breath chest discomfort",
    "chest heaviness breathing difficulty",
    "trouble taking deep breaths",
    "chest pressure breathing difficulty",
    "breathing discomfort chest tightness",
    "shortness breath chest pressure",
    "chest tightness difficulty breathing",
    "breathing problem chest discomfort",
    "difficulty breathing chest pain",
    "breathing difficulty chest discomfort",
    "shortness breath chest pressure",
    "chest pain trouble breathing",
    "difficulty breathing chest tightness",
    "chest pressure breathing difficulty",
    "shortness breath chest pain",
    "chest tightness shortness breath",
    "trouble breathing chest discomfort",
    "breathing problem chest pressure",
    "chest discomfort breathing problem",
    "difficulty breathing deeply",
    "heavy breathing chest tightness",
    "shortness breath chest discomfort",
    "chest pressure breathing problem",
    "breathing difficulty chest pain",
    "chest tightness breathing difficulty",
    "trouble taking deep breath",
    "chest heaviness shortness breath",
    "difficulty breathing chest pressure",
    "breathing discomfort chest pain",
    "shortness breath chest tightness",
    "chest pain breathing discomfort",
    "respiratory breathing difficulty",
    "chest pressure shortness breath",
    "difficulty breathing chest discomfort",
    "breathing trouble chest tightness",
    "chest tightness breathing trouble",
    "shortness breath chest pressure",
    "chest discomfort shortness breath",
    "breathing difficulty chest tightness",

    "itchy red skin",
    "skin redness itching",
    "red rash itching",
    "dry itchy skin",
    "skin rash redness",
    "itchy skin patches",
    "red skin patches",
    "skin irritation redness",
    "rash with itching",
    "itchy skin rash",
    "red itchy patches",
    "skin inflammation itching",
    "skin rash irritation",
    "persistent skin itching",
    "dry skin itching",
    "red irritated skin",
    "itching skin redness",
    "skin rash with redness",
    "itchy red patches",
    "skin irritation rash",
    "red skin irritation",
    "dry skin rash",
    "itchy skin redness",
    "skin rash itchy patches",
    "red rash on skin",
    "skin itching irritation",
    "persistent itchy rash",
    "skin redness rash",
    "itchy irritated patches",
    "rash and skin itching",
    "red dry itchy skin",
    "skin rash redness itching",
    "itchy red skin patches",
    "skin redness and rash",
    "dry itchy rash",
    "red irritated skin patches",
    "persistent skin rash itching",
    "skin itching redness",
    "rash with skin irritation",
    "itchy dry skin",
    "red itchy skin rash",
    "skin rash discomfort itching",
    "itchy red skin irritation",
    "skin patches redness",
    "dry skin redness itching",
    "skin rash itchy patches",
    "red skin itching discomfort",
    "itching with skin rash",
    "skin irritation and redness",
    "persistent itchy skin",
    "red rash skin irritation",
    "dry red itchy skin",
    "skin rash inflammation",
    "itchy skin red patches",
    "skin redness itchy rash",
    "rash irritation itching",
    "red skin rash patches",
    "skin dryness itching",
    "itching skin inflammation",
    "persistent red skin rash",
    "skin irritation itchy patches",

    "increased thirst frequent urination",
    "constant thirst weakness",
    "frequent urination tiredness",
    "excessive thirst fatigue",
    "thirst and frequent urination",
    "increased urination weakness",
    "constant thirst tiredness",
    "frequent urination fatigue",
    "unusual thirst weakness",
    "tiredness increased thirst",
    "frequent urination thirst",
    "excessive thirst weakness",
    "fatigue increased thirst",
    "frequent urination tiredness",
    "persistent thirst",
    "weakness increased thirst",
    "constant thirst frequent urination",
    "fatigue frequent urination",
    "increased thirst fatigue",
    "frequent urination weakness",
    "excessive thirst tiredness",
    "constant hunger frequent urination",
    "thirst weakness fatigue",
    "frequent urination excessive thirst",
    "persistent thirst tiredness",
    "increased thirst frequent urination fatigue",
    "weakness frequent urination thirst",
    "fatigue thirst weakness",
    "constant thirst frequent urination weakness",
    "unusual thirst frequent urination",
    "tiredness thirst frequent urination",
    "frequent urination increased thirst",
    "excessive thirst tiredness",
    "fatigue frequent urination",
    "constant thirst weakness",
    "increased thirst fatigue",
    "frequent urination weakness",
    "persistent thirst fatigue",
    "tiredness frequent urination",
    "unusual thirst frequent urination",
    "excessive thirst weakness",
    "fatigue increased urination",
    "constant thirst tiredness",
    "frequent urination fatigue weakness",
    "increased thirst weakness",
    "persistent thirst frequent urination",
    "tiredness excessive thirst",
    "frequent urination unusual thirst",
    "fatigue thirst frequent urination",
    "weakness thirst frequent urination",
    "constant thirst fatigue",
    "increased urination tiredness",
    "excessive thirst frequent urination",
    "frequent urination body weakness",
    "persistent thirst weakness",
    "fatigue unusual thirst",
    "increased thirst frequent urination weakness",
    "tiredness thirst weakness",
    "frequent urination increased thirst fatigue",
    "constant thirst frequent urination",
    "weakness excessive thirst tiredness"
]

labels = (
    ["Flu"] * 61 +
    ["Common Cold"] * 60 +
    ["Migraine"] * 60 +
    ["Stomach Infection"] * 60 +
    ["Respiratory Condition"] * 60 +
    ["Skin Condition"] * 60 +
    ["Diabetes Risk"] * 60
)

assert len(training_data) == len(labels)

vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    lowercase=True,
    min_df=1
)

X = vectorizer.fit_transform(training_data)

model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

model.fit(X, labels)

def get_model():
    return model, vectorizer